// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/MQEnergy/mqshop/internal/app/model"
)

func newMember(db *gorm.DB, opts ...gen.DOOption) member {
	_member := member{}

	_member.memberDo.UseDB(db, opts...)
	_member.memberDo.UseModel(&model.Member{})

	tableName := _member.memberDo.TableName()
	_member.ALL = field.NewAsterisk(tableName)
	_member.ID = field.NewInt64(tableName, "id")
	_member.UUID = field.NewString(tableName, "uuid")
	_member.Account = field.NewString(tableName, "account")
	_member.Password = field.NewString(tableName, "password")
	_member.Salt = field.NewString(tableName, "salt")
	_member.NickName = field.NewString(tableName, "nick_name")
	_member.RealName = field.NewString(tableName, "real_name")
	_member.Avatar = field.NewString(tableName, "avatar")
	_member.Sex = field.NewInt8(tableName, "sex")
	_member.Phone = field.NewString(tableName, "phone")
	_member.Birth = field.NewString(tableName, "birth")
	_member.RegisterIP = field.NewString(tableName, "register_ip")
	_member.RegisterTime = field.NewInt64(tableName, "register_time")
	_member.LoginIP = field.NewString(tableName, "login_ip")
	_member.LoginTime = field.NewInt64(tableName, "login_time")
	_member.Status = field.NewInt8(tableName, "status")
	_member.CreatedAt = field.NewInt64(tableName, "created_at")
	_member.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_member.fillFieldMap()

	return _member
}

// member 用户表
type member struct {
	memberDo

	ALL          field.Asterisk
	ID           field.Int64
	UUID         field.String // 唯一id号
	Account      field.String // 账号名称
	Password     field.String // 密码
	Salt         field.String // 加盐
	NickName     field.String // 昵称
	RealName     field.String // 真实姓名
	Avatar       field.String // 用户头像
	Sex          field.Int8   // 性别 0：未设置 1：男 2：女
	Phone        field.String // 手机号
	Birth        field.String // 出生日期
	RegisterIP   field.String // 注册ip
	RegisterTime field.Int64  // 注册时间
	LoginIP      field.String // 登录ip
	LoginTime    field.Int64  // 登录时间
	Status       field.Int8   // 状态 1：正常 0：禁用
	CreatedAt    field.Int64
	UpdatedAt    field.Int64

	fieldMap map[string]field.Expr
}

func (m member) Table(newTableName string) *member {
	m.memberDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m member) As(alias string) *member {
	m.memberDo.DO = *(m.memberDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *member) updateTableName(table string) *member {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UUID = field.NewString(table, "uuid")
	m.Account = field.NewString(table, "account")
	m.Password = field.NewString(table, "password")
	m.Salt = field.NewString(table, "salt")
	m.NickName = field.NewString(table, "nick_name")
	m.RealName = field.NewString(table, "real_name")
	m.Avatar = field.NewString(table, "avatar")
	m.Sex = field.NewInt8(table, "sex")
	m.Phone = field.NewString(table, "phone")
	m.Birth = field.NewString(table, "birth")
	m.RegisterIP = field.NewString(table, "register_ip")
	m.RegisterTime = field.NewInt64(table, "register_time")
	m.LoginIP = field.NewString(table, "login_ip")
	m.LoginTime = field.NewInt64(table, "login_time")
	m.Status = field.NewInt8(table, "status")
	m.CreatedAt = field.NewInt64(table, "created_at")
	m.UpdatedAt = field.NewInt64(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *member) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *member) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 18)
	m.fieldMap["id"] = m.ID
	m.fieldMap["uuid"] = m.UUID
	m.fieldMap["account"] = m.Account
	m.fieldMap["password"] = m.Password
	m.fieldMap["salt"] = m.Salt
	m.fieldMap["nick_name"] = m.NickName
	m.fieldMap["real_name"] = m.RealName
	m.fieldMap["avatar"] = m.Avatar
	m.fieldMap["sex"] = m.Sex
	m.fieldMap["phone"] = m.Phone
	m.fieldMap["birth"] = m.Birth
	m.fieldMap["register_ip"] = m.RegisterIP
	m.fieldMap["register_time"] = m.RegisterTime
	m.fieldMap["login_ip"] = m.LoginIP
	m.fieldMap["login_time"] = m.LoginTime
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m member) clone(db *gorm.DB) member {
	m.memberDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m member) replaceDB(db *gorm.DB) member {
	m.memberDo.ReplaceDB(db)
	return m
}

type memberDo struct{ gen.DO }

type IMemberDo interface {
	gen.SubQuery
	Debug() IMemberDo
	WithContext(ctx context.Context) IMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberDo
	WriteDB() IMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberDo
	Not(conds ...gen.Condition) IMemberDo
	Or(conds ...gen.Condition) IMemberDo
	Select(conds ...field.Expr) IMemberDo
	Where(conds ...gen.Condition) IMemberDo
	Order(conds ...field.Expr) IMemberDo
	Distinct(cols ...field.Expr) IMemberDo
	Omit(cols ...field.Expr) IMemberDo
	Join(table schema.Tabler, on ...field.Expr) IMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	Group(cols ...field.Expr) IMemberDo
	Having(conds ...gen.Condition) IMemberDo
	Limit(limit int) IMemberDo
	Offset(offset int) IMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo
	Unscoped() IMemberDo
	Create(values ...*model.Member) error
	CreateInBatches(values []*model.Member, batchSize int) error
	Save(values ...*model.Member) error
	First() (*model.Member, error)
	Take() (*model.Member, error)
	Last() (*model.Member, error)
	Find() ([]*model.Member, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Member, err error)
	FindInBatches(result *[]*model.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Member) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberDo
	Assign(attrs ...field.AssignExpr) IMemberDo
	Joins(fields ...field.RelationField) IMemberDo
	Preload(fields ...field.RelationField) IMemberDo
	FirstOrInit() (*model.Member, error)
	FirstOrCreate() (*model.Member, error)
	FindByPage(offset int, limit int) (result []*model.Member, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberDo) Debug() IMemberDo {
	return m.withDO(m.DO.Debug())
}

func (m memberDo) WithContext(ctx context.Context) IMemberDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberDo) ReadDB() IMemberDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberDo) WriteDB() IMemberDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberDo) Session(config *gorm.Session) IMemberDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberDo) Clauses(conds ...clause.Expression) IMemberDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberDo) Returning(value interface{}, columns ...string) IMemberDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberDo) Not(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberDo) Or(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberDo) Select(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberDo) Where(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberDo) Order(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberDo) Distinct(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberDo) Omit(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberDo) Join(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberDo) Group(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberDo) Having(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberDo) Limit(limit int) IMemberDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberDo) Offset(offset int) IMemberDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberDo) Unscoped() IMemberDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberDo) Create(values ...*model.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberDo) CreateInBatches(values []*model.Member, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberDo) Save(values ...*model.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberDo) First() (*model.Member, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Take() (*model.Member, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Last() (*model.Member, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Find() ([]*model.Member, error) {
	result, err := m.DO.Find()
	return result.([]*model.Member), err
}

func (m memberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Member, err error) {
	buf := make([]*model.Member, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberDo) FindInBatches(result *[]*model.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberDo) Attrs(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberDo) Assign(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberDo) Joins(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberDo) Preload(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberDo) FirstOrInit() (*model.Member, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) FirstOrCreate() (*model.Member, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) FindByPage(offset int, limit int) (result []*model.Member, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberDo) Delete(models ...*model.Member) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberDo) withDO(do gen.Dao) *memberDo {
	m.DO = *do.(*gen.DO)
	return m
}
