server:
  mode: 'test'
  defaultPageSize: 10 # 默认分页条数
  maxPageSize: 500    # 最大分页条数
  fileUploadPath: 'upload' # 文件上传路径
  fileHostUrl: 'http://mqshop-backend.yippai.com/' # 文件访问域名
  whiteList: '*' # 白名单
  originList: '*' # cors地址列表以逗号相隔 默认* 按需配置如：https://example1.com,https://example2.com,
  superRoleId: 1 # 超级管理员角色ID
jwt:
  expire: 864000   # token过期时间 单位：s
  issuer: 'mqshop'
  secret: '3jQSRZXeXzr09hq0G1ZuL9Dgtk2XV9Ax'
  authScheme: 'Bearer'
  tokenLookup: 'header:Authorization' # Possible values: "header:<name>"、"query:<name>"、"param:<name>"、"cookie:<name>"
log:
  level: -4 # 日志级别 debug: -4, info: 0, warn: 4, error: 8
  fileName: 'mqshop' # 日志文件名称
  dirPath: 'runtime/logs' # 日志默认存放目录
  maxSize: 1 # 日志最大存储大小 1M
  maxAge: 1 # 保留日志最大天数 1天
  maxBackups: 3 # 保留日志最大数量 3个
  localTime: true # 是否使用本地时间
  compress: true # 是否压缩归档日志
database:
  mysql:
    enabled: true # 是否启用mysql
    maxIdleConn: 10 # 设置空闲连接池中连接的最大数量
    maxOpenConn: 100 # 设置打开数据库连接的最大数量
    maxLifeTime: 60 # 设置连接可复用的最大时间（分钟）
    maxIdleTime: 0 # 设置连接池中保持空闲的最长时间（秒）默认是0 意味着连接池中的连接将保持打开状态
    sources: # 数据库配置 需要配置多个数据库 复制default以下模板
      default: # 默认数据库 (此名称切勿修改)
        separation: false # 配置是否使用读写分离，方便改配置切换
        fileName: 'default-sql' # 日志文件名称 【需修改】
        logLevel: 1 # 日志模式 1:slient 2:error 3:warn 4:info
        prefix: "ms_"
        master: 'root:%40K%216Rggurg6JH%24vV@tcp(127.0.0.1:3306)/o2o?charset=utf8mb4&parseTime=True&loc=Local' # dyq
        slave:
          - 'root:%40K%216Rggurg6JH%24vV@tcp(127.0.0.1:3306)/o2o?charset=utf8mb4&parseTime=True&loc=Local' # dyq 47.100.59.183
  mongo:
    enable: false
    uri:
    minPoolSize: 10
    maxPoolSize: 20
redis:
  enabled: true # 是否启用redis
  host: '127.0.0.1'
  port: '6379'
  password: '123456'
  dbNum: 0
  prefix: 'mqshop:' # 登录用户存入redis键名的前缀
  poolSize: 20
  maxIdleConn: 30
  minIdleConn: 10
  maxIdleTime: 30   # 单位（分）
  maxLifeTime: 60   # 单位（秒）
amqp:
  enabled: true # 是否启用rabbitmq
  host: '127.0.0.1'
  port: '5672'
  user: 'guest'
  password: ''
  vhost: ''
oss:
  endPoint: 'https://oss-cn-shanghai.aliyuncs.com'
  accessKeyId: ''
  accessKeySecret: ''
  bucketName: ''
wecom: # 企业微信
  corpId: ''  # 企业ID
  corpSecret: '' # 企业微信应用密钥
  agentId:  # 企业微信应用ID
  oauthCallback: '' # 企业微信回调地址