// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBanner = "ms_banner"

// Banner 轮播图表
type Banner struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CateID    int64  `gorm:"column:cate_id;type:bigint unsigned;not null;comment:分类ID" json:"cate_id"`             // 分类ID
	Title     string `gorm:"column:title;type:varchar(64);not null;comment:标题" json:"title"`                       // 标题
	Subtitle  string `gorm:"column:subtitle;type:varchar(128);not null;comment:副标题" json:"subtitle"`               // 副标题
	PicURL    string `gorm:"column:pic_url;type:varchar(128);not null;comment:图片地址" json:"pic_url"`                // 图片地址
	LinkURL   string `gorm:"column:link_url;type:varchar(128);not null;comment:图片跳转链接地址" json:"link_url"`          // 图片跳转链接地址
	SortOrder int    `gorm:"column:sort_order;type:int unsigned;not null;default:50;comment:排序" json:"sort_order"` // 排序
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt *int64 `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
