// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCStreets = "ms_c_streets"

// CStreets mapped from table <ms_c_streets>
type CStreets struct {
	ID           int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Code         *string `gorm:"column:code;type:varchar(255)" json:"code"`
	Name         *string `gorm:"column:name;type:varchar(255)" json:"name"`
	AreaCode     *string `gorm:"column:area_code;type:varchar(255)" json:"area_code"`
	ProvinceCode *string `gorm:"column:province_code;type:varchar(255)" json:"province_code"`
	CityCode     *string `gorm:"column:city_code;type:varchar(255)" json:"city_code"`
}

// TableName CStreets's table name
func (*CStreets) TableName() string {
	return TableNameCStreets
}
