// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberInfo = "ms_member_info"

// MemberInfo 用户详情表
type MemberInfo struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID  int64  `gorm:"column:member_id;type:bigint unsigned;not null;comment:用户ID" json:"member_id"` // 用户ID
	PostNum   int    `gorm:"column:post_num;type:int unsigned;not null;comment:帖子数量" json:"post_num"`      // 帖子数量
	LikedNum  int    `gorm:"column:liked_num;type:int unsigned;not null;comment:获赞数" json:"liked_num"`     // 获赞数
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt *int64 `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName MemberInfo's table name
func (*MemberInfo) TableName() string {
	return TableNameMemberInfo
}
