// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberPostTagRelation = "ms_member_post_tag_relation"

// MemberPostTagRelation 帖子标签关联表
type MemberPostTagRelation struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	PostID    int64  `gorm:"column:post_id;type:bigint unsigned;not null;comment:帖子ID" json:"post_id"` // 帖子ID
	TagID     int64  `gorm:"column:tag_id;type:bigint unsigned;not null;comment:标签ID" json:"tag_id"`   // 标签ID
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
}

// TableName MemberPostTagRelation's table name
func (*MemberPostTagRelation) TableName() string {
	return TableNameMemberPostTagRelation
}
