// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberPost = "ms_member_post"

// MemberPost 用户帖子列表
type MemberPost struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID  int64  `gorm:"column:member_id;type:bigint unsigned;not null;comment:用户ID" json:"member_id"` // 用户ID
	Desc      string `gorm:"column:desc;type:varchar(255);not null;comment:内容" json:"desc"`                // 内容
	LinkURL   string `gorm:"column:link_url;type:varchar(128);not null;comment:链接地址" json:"link_url"`      // 链接地址
	PicURL    string `gorm:"column:pic_url;type:varchar(255);not null;comment:图片地址[1,2]" json:"pic_url"`   // 图片地址[1,2]
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt *int64 `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName MemberPost's table name
func (*MemberPost) TableName() string {
	return TableNameMemberPost
}
