// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberThirdAuth = "ms_member_third_auth"

// MemberThirdAuth 用户三方授权表
type MemberThirdAuth struct {
	ID           int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID     int64  `gorm:"column:member_id;type:bigint unsigned;not null;comment:用户ID" json:"member_id"`                                    // 用户ID
	NickName     string `gorm:"column:nick_name;type:varchar(64);not null;comment:昵称" json:"nick_name"`                                          // 昵称
	Avatar       string `gorm:"column:avatar;type:varchar(255);not null;comment:用户头像" json:"avatar"`                                             // 用户头像
	Gender       int8   `gorm:"column:gender;type:tinyint unsigned;not null;comment:性别 0：未设置 1：男 2：女" json:"gender"`                             // 性别 0：未设置 1：男 2：女
	City         string `gorm:"column:city;type:varchar(64);not null;comment:城市" json:"city"`                                                    // 城市
	Province     string `gorm:"column:province;type:varchar(64);not null;comment:省份" json:"province"`                                            // 省份
	Country      string `gorm:"column:country;type:varchar(64);not null;comment:国家" json:"country"`                                              // 国家
	Openid       string `gorm:"column:openid;type:varchar(64);not null;comment:用户唯一标识" json:"openid"`                                            // 用户唯一标识
	SessionKey   string `gorm:"column:session_key;type:varchar(64);not null;comment:会话秘钥" json:"session_key"`                                    // 会话秘钥
	Unionid      string `gorm:"column:unionid;type:varchar(64);not null;comment:用户在开放平台的唯一标识符" json:"unionid"`                                   // 用户在开放平台的唯一标识符
	PlatformType int8   `gorm:"column:platform_type;type:tinyint unsigned;not null;default:1;comment:平台标识 1：微信小程序 2：微信公众号" json:"platform_type"` // 平台标识 1：微信小程序 2：微信公众号
	CreatedAt    *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
}

// TableName MemberThirdAuth's table name
func (*MemberThirdAuth) TableName() string {
	return TableNameMemberThirdAuth
}
