// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductGoodsSku = "ms_product_goods_sku"

// ProductGoodsSku 商品sku配置表
type ProductGoodsSku struct {
	ID           int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	GoodsID      int64   `gorm:"column:goods_id;type:bigint unsigned;not null;comment:商品ID" json:"goods_id"`                       // 商品ID
	Price        float64 `gorm:"column:price;type:decimal(10,2);not null;comment:销售价格" json:"price"`                               // 销售价格
	Stock        int     `gorm:"column:stock;type:int;not null;comment:商品库存" json:"stock"`                                         // 商品库存
	StockWarning int     `gorm:"column:stock_warning;type:int;not null;comment:库存预警值" json:"stock_warning"`                        // 库存预警值
	SkuNo        string  `gorm:"column:sku_no;type:varchar(32);not null;default:0;comment:sku编码" json:"sku_no"`                    // sku编码
	ThumbURL     string  `gorm:"column:thumb_url;type:varchar(128);not null;comment:图片" json:"thumb_url"`                          // 图片
	AttrValue    string  `gorm:"column:attr_value;type:varchar(255);not null;comment:属性值 {"1":"金色", "2":"16G"}" json:"attr_value"` // 属性值 {"1":"金色", "2":"16G"}
	AttrHash     string  `gorm:"column:attr_hash;type:varchar(255);not null;comment:属性值对应的hash值" json:"attr_hash"`                 // 属性值对应的hash值
	CreatedAt    *int64  `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt    *int64  `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName ProductGoodsSku's table name
func (*ProductGoodsSku) TableName() string {
	return TableNameProductGoodsSku
}
