// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductGoodsAttr = "ms_product_goods_attr"

// ProductGoodsAttr 商品属性配置表
type ProductGoodsAttr struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CateID    int64  `gorm:"column:cate_id;type:bigint unsigned;not null;comment:属性分类ID" json:"cate_id"`                      // 属性分类ID
	AttrType  int8   `gorm:"column:attr_type;type:tinyint unsigned;not null;comment:属性类型 1：属性 2：参数" json:"attr_type"`         // 属性类型 1：属性 2：参数
	AttrName  string `gorm:"column:attr_name;type:varchar(32);not null;comment:属性名 如：颜色" json:"attr_name"`                    // 属性名 如：颜色
	AttrValue string `gorm:"column:attr_value;type:varchar(255);not null;comment:属性值 黄色,红色,白色..." json:"attr_value"`          // 属性值 黄色,红色,白色...
	InputType int8   `gorm:"column:input_type;type:tinyint unsigned;not null;comment:录入方式 1：手工录入 2：从列表中选择" json:"input_type"` // 录入方式 1：手工录入 2：从列表中选择
	SortOrder int    `gorm:"column:sort_order;type:int unsigned;not null;default:50;comment:排序" json:"sort_order"`            // 排序
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt *int64 `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName ProductGoodsAttr's table name
func (*ProductGoodsAttr) TableName() string {
	return TableNameProductGoodsAttr
}
