// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductGoodsSkuAttrRelation = "ms_product_goods_sku_attr_relation"

// ProductGoodsSkuAttrRelation 商品sku属性关联表
type ProductGoodsSkuAttrRelation struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	SkuID     int64  `gorm:"column:sku_id;type:bigint unsigned;not null;comment:skuID" json:"sku_id"`                 // skuID
	AttrID    int64  `gorm:"column:attr_id;type:bigint unsigned;not null;comment:属性ID" json:"attr_id"`                // 属性ID
	AttrName  string `gorm:"column:attr_name;type:varchar(255);not null;comment:商品属性名称 如：颜色" json:"attr_name"`        // 商品属性名称 如：颜色
	AttrValue string `gorm:"column:attr_value;type:varchar(255);not null;comment:商品属性值 如：金色,银色,黄色" json:"attr_value"` // 商品属性值 如：金色,银色,黄色
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
}

// TableName ProductGoodsSkuAttrRelation's table name
func (*ProductGoodsSkuAttrRelation) TableName() string {
	return TableNameProductGoodsSkuAttrRelation
}
