// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductGoodsInfo = "ms_product_goods_info"

// ProductGoodsInfo 商品详情表
type ProductGoodsInfo struct {
	ID                   int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	GoodsID              int64   `gorm:"column:goods_id;type:bigint unsigned;not null;comment:商品ID" json:"goods_id"`                                     // 商品ID
	Unit                 string  `gorm:"column:unit;type:varchar(32);not null;comment:计量单位" json:"unit"`                                                 // 计量单位
	Weight               float64 `gorm:"column:weight;type:decimal(8,2);not null;default:0.00;comment:商品重量 kg" json:"weight"`                            // 商品重量 kg
	Integral             int     `gorm:"column:integral;type:int unsigned;not null;comment:积分" json:"integral"`                                          // 积分
	DetailTitle          string  `gorm:"column:detail_title;type:varchar(255);not null;comment:详细页标题" json:"detail_title"`                               // 详细页标题
	DetailDesc           string  `gorm:"column:detail_desc;type:varchar(255);not null;comment:详细页描述" json:"detail_desc"`                                 // 详细页描述
	GoodsKeyword         string  `gorm:"column:goods_keyword;type:varchar(255);not null;comment:商品关键字" json:"goods_keyword"`                             // 商品关键字
	GoodsContent         string  `gorm:"column:goods_content;type:longtext;not null;comment:商品详情" json:"goods_content"`                                  // 商品详情
	ShippingFee          float64 `gorm:"column:shipping_fee;type:decimal(8,2);not null;default:0.00;comment:快递费" json:"shipping_fee"`                    // 快递费
	CurMonthSaleNum      int     `gorm:"column:cur_month_sale_num;type:int unsigned;not null;comment:当月销量" json:"cur_month_sale_num"`                    // 当月销量
	ShippingProvinceID   int     `gorm:"column:shipping_province_id;type:int unsigned;not null;comment:商品发货地省份ID" json:"shipping_province_id"`           // 商品发货地省份ID
	ShippingProvinceName string  `gorm:"column:shipping_province_name;type:varchar(32);not null;comment:商品发货地省份名称" json:"shipping_province_name"`        // 商品发货地省份名称
	ShippingCityID       int     `gorm:"column:shipping_city_id;type:int unsigned;not null;comment:商品发货地城市ID" json:"shipping_city_id"`                   // 商品发货地城市ID
	ShippingCityName     string  `gorm:"column:shipping_city_name;type:varchar(32);not null;comment:商品发货地城市名称" json:"shipping_city_name"`                // 商品发货地城市名称
	ShippingRemark       string  `gorm:"column:shipping_remark;type:varchar(128);not null;comment:配送费标记如：在线支付免运费" json:"shipping_remark"`                // 配送费标记如：在线支付免运费
	GoodsRemark          string  `gorm:"column:goods_remark;type:varchar(128);not null;comment:商品标记如：可配送海外，店铺发货，7天无理由退货，闪电退款，极速审核等" json:"goods_remark"` // 商品标记如：可配送海外，店铺发货，7天无理由退货，闪电退款，极速审核等
	ServiceInfo          string  `gorm:"column:service_info;type:varchar(128);not null;comment:商品服务如：可配送海外，店铺发货，7天无理由退货，闪电退款，极速审核等" json:"service_info"` // 商品服务如：可配送海外，店铺发货，7天无理由退货，闪电退款，极速审核等
	IsShow               int8    `gorm:"column:is_show;type:tinyint unsigned;not null;default:1;comment:商品详情是否展示 1：展示 0：不展示" json:"is_show"`             // 商品详情是否展示 1：展示 0：不展示
	ViewNum              int     `gorm:"column:view_num;type:int unsigned;not null;comment:商品浏览数量" json:"view_num"`                                      // 商品浏览数量
	CollectNum           int     `gorm:"column:collect_num;type:int unsigned;not null;comment:商品收藏数量" json:"collect_num"`                                // 商品收藏数量
	LikeNum              int     `gorm:"column:like_num;type:int unsigned;not null;comment:商品点赞数量" json:"like_num"`                                      // 商品点赞数量
	CreatedAt            *int64  `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt            *int64  `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName ProductGoodsInfo's table name
func (*ProductGoodsInfo) TableName() string {
	return TableNameProductGoodsInfo
}
