// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductGoods = "ms_product_goods"

// ProductGoods 商品表
type ProductGoods struct {
	ID            int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	UUID          string  `gorm:"column:uuid;type:varchar(32);not null;comment:唯一id号" json:"uuid"`                                  // 唯一id号
	GoodsTitle    string  `gorm:"column:goods_title;type:varchar(128);not null;comment:商品标题" json:"goods_title"`                    // 商品标题
	GoodsSubtitle string  `gorm:"column:goods_subtitle;type:varchar(128);not null;comment:商品小标题" json:"goods_subtitle"`             // 商品小标题
	CateID        int64   `gorm:"column:cate_id;type:bigint unsigned;not null;comment:分类ID" json:"cate_id"`                         // 分类ID
	BrandID       int64   `gorm:"column:brand_id;type:bigint unsigned;not null;comment:品牌ID" json:"brand_id"`                       // 品牌ID
	AttrCateID    int64   `gorm:"column:attr_cate_id;type:bigint unsigned;not null;comment:属性分类ID" json:"attr_cate_id"`             // 属性分类ID
	ThumbURL      string  `gorm:"column:thumb_url;type:varchar(255);not null;comment:商品缩略图图片" json:"thumb_url"`                     // 商品缩略图图片
	PhotoUrls     string  `gorm:"column:photo_urls;type:text;not null;comment:商品相册图列表" json:"photo_urls"`                           // 商品相册图列表
	OriginPrice   float64 `gorm:"column:origin_price;type:decimal(10,2);not null;default:0.00;comment:商品原价" json:"origin_price"`    // 商品原价
	PromotePrice  float64 `gorm:"column:promote_price;type:decimal(10,2);not null;default:0.00;comment:商品促销价" json:"promote_price"` // 商品促销价
	FinalPrice    float64 `gorm:"column:final_price;type:decimal(10,2);not null;default:0.00;comment:商品最终价" json:"final_price"`     // 商品最终价
	TotalStock    int     `gorm:"column:total_stock;type:int;not null;comment:总库存" json:"total_stock"`                              // 总库存
	IsHot         int8    `gorm:"column:is_hot;type:tinyint unsigned;not null;comment:是否热门 1：热门 0：正常" json:"is_hot"`                // 是否热门 1：热门 0：正常
	IsNew         int8    `gorm:"column:is_new;type:tinyint unsigned;not null;comment:是否新品 1：新品 0：正常" json:"is_new"`                // 是否新品 1：新品 0：正常
	IsRecommend   int8    `gorm:"column:is_recommend;type:tinyint unsigned;not null;comment:是否推荐 1：热门 0：正常" json:"is_recommend"`    // 是否推荐 1：热门 0：正常
	SortOrder     int     `gorm:"column:sort_order;type:int unsigned;not null;default:50;comment:排序" json:"sort_order"`             // 排序
	Status        int8    `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1：正常 0：下架" json:"status"`        // 状态 1：正常 0：下架
	CreatedAt     *int64  `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt     *int64  `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName ProductGoods's table name
func (*ProductGoods) TableName() string {
	return TableNameProductGoods
}
