// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePostComment = "ms_post_comment"

// PostComment 帖子评论表
type PostComment struct {
	ID         int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID   int64  `gorm:"column:member_id;type:bigint unsigned;not null;comment:用户ID" json:"member_id"`  // 用户ID
	MemberName string `gorm:"column:member_name;type:varchar(255);not null;comment:用户名称" json:"member_name"` // 用户名称
	PostID     int64  `gorm:"column:post_id;type:bigint unsigned;not null;comment:帖子ID" json:"post_id"`      // 帖子ID
	Content    string `gorm:"column:content;type:varchar(255);not null;comment:评论内容" json:"content"`         // 评论内容
	LikeNum    int    `gorm:"column:like_num;type:int unsigned;not null;comment:评论点赞数" json:"like_num"`      // 评论点赞数
	CreatedAt  *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
	UpdatedAt  *int64 `gorm:"column:updated_at;type:bigint unsigned" json:"updated_at"`
}

// TableName PostComment's table name
func (*PostComment) TableName() string {
	return TableNamePostComment
}
