// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsCode = "ms_sms_code"

// SmsCode 短信验证码表
type SmsCode struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Code      string `gorm:"column:code;type:varchar(16);not null;comment:验证码" json:"code"`                     // 验证码
	Phone     string `gorm:"column:phone;type:varchar(16);not null;comment:手机号码" json:"phone"`                  // 手机号码
	Status    int8   `gorm:"column:status;type:tinyint unsigned;not null;comment:状态 0：未使用 1：已使用" json:"status"` // 状态 0：未使用 1：已使用
	CreatedAt *int64 `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
}

// TableName SmsCode's table name
func (*SmsCode) TableName() string {
	return TableNameSmsCode
}
