// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbOriginGoods = "ms_tb_origin_goods"

// TbOriginGoods 淘宝商品源数据表
type TbOriginGoods struct {
	ID                   int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	GoodsTitle           string  `gorm:"column:goods_title;type:varchar(128);not null;comment:商品标题" json:"goods_title"`                           // 商品标题
	FinalPrice           float64 `gorm:"column:final_price;type:decimal(10,2);not null;default:0.00;comment:商品最终价" json:"final_price"`            // 商品最终价
	TotalStock           int     `gorm:"column:total_stock;type:int;not null;comment:总库存" json:"total_stock"`                                     // 总库存
	ThumbURL             string  `gorm:"column:thumb_url;type:varchar(255);not null;comment:商品缩略图图片" json:"thumb_url"`                            // 商品缩略图图片
	PhotoUrls            string  `gorm:"column:photo_urls;type:text;not null;comment:商品相册图列表" json:"photo_urls"`                                  // 商品相册图列表
	IsNew                int8    `gorm:"column:is_new;type:tinyint unsigned;not null;comment:是否新品 1：新品 0：正常" json:"is_new"`                       // 是否新品 1：新品 0：正常
	DetailTitle          string  `gorm:"column:detail_title;type:varchar(255);not null;comment:详细页标题" json:"detail_title"`                        // 详细页标题
	ShippingProvinceID   int     `gorm:"column:shipping_province_id;type:int unsigned;not null;comment:商品发货地省份ID" json:"shipping_province_id"`    // 商品发货地省份ID
	ShippingProvinceName string  `gorm:"column:shipping_province_name;type:varchar(32);not null;comment:商品发货地省份名称" json:"shipping_province_name"` // 商品发货地省份名称
	ShippingCityID       int     `gorm:"column:shipping_city_id;type:int unsigned;not null;comment:商品发货地城市ID" json:"shipping_city_id"`            // 商品发货地城市ID
	ShippingCityName     string  `gorm:"column:shipping_city_name;type:varchar(32);not null;comment:商品发货地城市名称" json:"shipping_city_name"`         // 商品发货地城市名称
	GoodsContent         string  `gorm:"column:goods_content;type:longtext;not null;comment:商品详情" json:"goods_content"`                           // 商品详情
	Status               int8    `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:同步状态 1：未同步 2：已同步" json:"status"`           // 同步状态 1：未同步 2：已同步
	CreatedAt            *int64  `gorm:"column:created_at;type:bigint unsigned" json:"created_at"`
}

// TableName TbOriginGoods's table name
func (*TbOriginGoods) TableName() string {
	return TableNameTbOriginGoods
}
